pull_request_rules:
  - name: "Automatic merge when CI passes and approved"
    conditions:
      - "#approved-reviews-by>=1"
      - "check-success=check-required-labels"
      - "base=main"
    actions:
      merge: