pull_request_rules:
  - name: "Automatic merge when CI passes and approved"
    conditions:
      -  check-success=check-required-labels
      -  base=main
    actions:
      queue:
  - name: Dismiss reviews when review is requested
    conditions:
      - base=main
    actions:
      dismiss_reviews:
        approved: from_requested_reviewers
        changes_requested: from_requested_reviewers
        when: always
        message: "Review dismissed due to new review request."
queue_rules:
  - name: urgent
    # This can be queued before CI finishes its first run if the PR has the urgent label
    queue_conditions:
      - label = urgent
    # We still want the CI to pass to merge the PR
    merge_conditions:
      - "#approved-reviews-by>=1"
  - name: standard
    # CI is needed for queueing and merging the PR
    merge_conditions:
      - "#approved-reviews-by>=1"